# WITH TOTAL_SALE_AMOUNT AS 
#      (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
#       FROM OFFLINE_SALE
#       GROUP BY PRODUCT_ID)


# SELECT PRODUCT_CODE, (A.PRICE * B.AMOUNT) AS SALES
# FROM PRODUCT AS A
# JOIN TOTAL_SALE_AMOUNT AS B
# ON A.PRODUCT_ID = B.PRODUCT_ID
# ORDER BY 2 DESC, 1 ASC

SELECT P.PRODUCT_CODE,
       SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT P 
INNER JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;