WITH TOTAL_SALE_AMOUNT AS 
     (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID)


SELECT PRODUCT_CODE, (A.PRICE * B.AMOUNT) AS SALES
FROM PRODUCT AS A
JOIN TOTAL_SALE_AMOUNT AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 2 DESC, 1 ASC