-- CARTS 테이블의 product_count 컬럼 장바구니에 담긴 수를 캐싱하는 상품. 이 컬럼이 업데이트 되지 않는 버그. 캐싱이 잘못된 아이디, 잘못 들어간 값, 올바른 값을 조회하는 SQL?
-- 장바구니 아이디 수
-- CARTS: ID, USER_ID, PAYED_AT, PRODUCT_COUNT
-- CART_PRODUCTS: ID, CART_ID, NAME, PRICE

SELECT ID, PRODUCT_ID AS WRONG, CRT.CORRECT
FROM CARTS, (
    SELECT COUNT(CART_ID) AS CORRECT, CART_ID
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) AS CRT
WHERE CARTS.ID = CRT.CART_ID AND CARTS.PRODUCT_COUNT != CRT.CORRECT
ORDER BY CART_ID

-- 맞는 코드
SELECT C.ID, C.PRODUCT_COUNT AS WRONG, NVL(CRT.CORRECT, 0) AS CORRECT
FROM CARTS C
LEFT JOIN (
    SELECT CART_ID, COUNT(*) AS CORRECT
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) CRT ON C.ID = CRT.CART_ID
WHERE C.PRODUCT_COUNT != NVL(CRT.CORRECT, 0)
ORDER BY C.ID;
