-- CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 자동차 종류가 '세단' 또는 'SUV' 인 
-- 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 
-- 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문을 작성해주세요. 
-- 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 
-- 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬해주세요.

-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 불가능한 차량 ID 
WITH CANT_RENTAL AS (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
    DATE_FORMAT(START_DATE, '%Y-%m') = '2022-11' OR 
    DATE_FORMAT(END_DATE, '%Y-%m') = '2022-11' OR 
    (START_DATE < '2022-11-01' AND END_DATE >= '2022-12-01')
),
DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE	= '30일 이상'
)
SELECT C.CAR_ID, C.CAR_TYPE, 
CONVERT((C.DAILY_FEE * 30) * (100 - D.DISCOUNT_RATE) / 100 , UNSIGNED) FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN DISCOUNT D 
ON C.CAR_TYPE = D.CAR_TYPE 
WHERE C.CAR_ID NOT IN (SELECT * FROM CANT_RENTAL)
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2 ASC , 1 DESC

/*  대여 중인 자동차들의 정보 CAR_RENTAL_COMPANY_CAR
    자동차 대여 기록 정보 CAR_RENTAL_COMPANY_RENTAL_HISTORY
    자동차 종류 별 대여 기간 종류 별 할인 정책 정보 CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
    2022년 11월 1일부터 2022년 11월 30일까지 대여 가능 
    30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
    자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
    대여 금액을 기준으로 내림차순
    대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순
    자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순*/


WITH DAY AS 
    (SELECT CAR_ID, START_DATE, END_DATE
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'))



SELECT A.CAR_ID, A.CAR_TYPE,  ROUND((DAILY_FEE * (1-(0.01* DISCOUNT_RATE))),0) * 30 AS FEE
FROM DAY AS D
JOIN 

(SELECT CAR_ID, CAR_TYPE, DAILY_FEE
       FROM CAR_RENTAL_COMPANY_CAR
       WHERE CAR_TYPE IN ('세단', 'SUV')) AS A

ON D.CAR_ID = A.CAR_ID

JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE C.DURATION_TYPE = '30일 이상'
GROUP BY CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC