SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT;

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

SELECT *
FROM food_product
ORDER BY PRICE DESC
LIMIT 1

SELECT MAX(DATETIME) 
FROM ANIMAL_INS

SELECT MIN(DATETIME)
FROM ANIMAL_INS;

SELECT COUNT(*) ANIMAL_ID
FROM ANIMAL_INS;
-- COUNT 함수

SELECT COUNT(DISTINCT(NAME)) 
FROM ANIMAL_INS;

SELECT SUM(PRICE) TOTAL_PRICE
FROM ITEM_INFO
WHERE RARITY = 'LEGEND'

SELECT SUM(PRICE) TOTAL_PRICE
FROM ITEM_INFO
GROUP BY RARITY
HAVING RARITY = 'LEGEND'

SELECT ID
     , FISH_NAME
     , LENGTH
FROM FISH_INFO I 
        JOIN 
     FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) 
                                FROM FISH_INFO
                                GROUP BY FISH_TYPE)
ORDER BY ID

SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH
FROM FISH_INFO;

-- 분화된 연도(YEAR), 분화된 연도별 대장균 크기의 편차(YEAR_DEV), 대장균 개체의 ID(ID) 를 출력하는 SQL 문을 작성해주세요. 
-- 분화된 연도별 대장균 크기의 편차는 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기로 구하며 
-- 결과는 연도에 대해 오름차순으로 정렬하고 같은 연도에 대해서는 대장균 크기의 편차에 대해 오름차순으로 정렬해주세요.
SELECT B.YEAR AS YEAR, 
        MAX_SIZE-A.SIZE_OF_COLONY AS YEAR_DEV, 
        ID
    FROM ECOLI_DATA A, ( SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
                            FROM ECOLI_DATA
                            GROUP BY YEAR ) B
    WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
    -- ORDER BY 1, 2
    ORDER BY YEAR ASC, YEAR_DEV ASC;